### ISSUE TITLE
fi_FI.csv file is empty

### ISSUE THREAD

**Issue by keivan85** [mageplaza/magento-2-finnish-language-pack#4]
Hi,
Is there a reason that all Finnish translation are deleted?
according to this commit https://github.com/mageplaza/magento-2-finnish-language-pack/commit/e2e9ebb7c3b3ed07cf7af7b2b4b0d9e3f9f3f672
about 15000 lines of translation are removed and now the fi_FI.csv file is empty.

**Comment by Nastradoomus** [comment]
Yes exactly. What happened here after 2.3 update?

**Comment by MyoDaisy** [comment]
Thank you for reporting the problem.
I have updated **fi_FI.csv** file, you can reinstall it.
Really sorry for this issue.
